# Spring
spring:
  datasource:
    url: jdbc:mysql://10.0.97.95:3308/steam_iam?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: choerodon
    password: ApcWJdstaw
  aop:
    auto: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
#  redis:
#    host: localhost
#    port: 6379
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  mvc:
    async:
      request-timeout: 200000
# Mybatis
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  global-config:
    db-config:
      idType: AUTO

# 注册中心
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      # 开发环境地址
      defaultZone: http://10.0.49.90:8000/eureka/
    registryFetchIntervalSeconds: 10
# Choerodon
choerodon:
  saga:
    consumer:
      enabled: true # 是否启用消费端
      thread-num: 5  # 消费线程数
      max-poll-size: 200 # 每次拉取的最大消息数量
      poll-interval-ms: 10000 # 拉取消息的间隔(毫秒)，默认1000毫秒
  schedule:
    consumer:
      enabled: true # 启用任务调度消费端
      thread-num: 1 # 任务调度消费线程数
      poll-interval-ms: 1000 # 拉取间隔，默认1000毫秒
  devops:
    message: true # 开启事务信息
    conditionDate: 2019-12-10 14:59 # ChoerodonDevOpsProperties#conditionDate
services:
  attachment:
    url: http://minio.steamsit.crcloud.com/iam-service/
  agile:
    host: http://iam.steamsit.crcloud.com
# Feign,远程调用
feign:
  hystrix:
    shareSecurityContext: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 30000
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
logging:
  level:
    root: INFO
    io.choerodon.test.manager: debug
    com:
      netflix:
        discovery: ERROR
      crc:
        crcloud:
          steam:
            iam:
              dao: debug
